# Generated by Django 4.0.2 on 2022-02-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_measurement_sensor_id_measurement_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(max_length=60, null=True, upload_to=''),
        ),
    ]
